name: Build and Test

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install Linux dependencies
          if: runner.os == 'Linux'
          run: |
            sudo apt-get update
        
        - name: Setup Conan
          uses: conan-io/setup-conan@v1
          with:
            cache_packages: true

        - name: Install Conan dependencies (Linux)
          if: runner.os == 'Linux'
          run: |
            CC=clang CXX=clang++ conan install . --build=missing -s build_type=Release -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
        
        - name: Install Conan dependencies (macOS)
          if: runner.os == 'macOS'
          run: |
            CC=clang CXX=clang++ conan install . --build=missing -s build_type=Release

        - name: Build with CMake
          run: |
            cmake -S . -B build/Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
            cmake --build build/Release
        
        - name: Run tests
          working-directory: ./build/Release
          run: ctest --output-on-failure
