name: Build and Test

on:
    push:
        branches: [ "master" ]
        tags:
            'v*.*.*'
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        runs-on: ${{ matrix.os }}

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Run apt-get update
          if: runner.os == 'Linux'
          run: |
            sudo apt-get update
            sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
        
        - name: Setup Conan
          uses: conan-io/setup-conan@v1
          with:
            cache_packages: true

        - name: Install Conan dependencies (Linux)
          if: runner.os == 'Linux'
          run: |
            CC=clang CXX=clang++ conan install . --build=missing -s build_type=Release -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
        
        - name: Install Conan dependencies (macOS)
          if: runner.os == 'macOS'
          run: |
            CC=clang CXX=clang++ conan install . --build=missing -s build_type=Release

        - name: Install Conan dependencies (Windows)
          if: runner.os == 'Windows'
          run: conan install . --build=missing -s build_type=Release

        - name: Build with CMake
          if: runner.os != 'Windows'
          run: |
            cmake --preset conan-release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
            cmake --build build/Release

        - name: Build with CMake (Windows)
          if: runner.os == 'Windows'
          run: |
            cmake --preset conan-default -DCMAKE_BUILD_TYPE=Release
            cmake --build build --config Release

        - name: Run tests
          if: runner.os != 'Windows'
          working-directory: ./build/Release
          run: ctest -C Release --output-on-failure

        - name: Run tests (Windows)
          if: runner.os == 'Windows'
          working-directory: ./build
          run: ctest -C Release --output-on-failure

        - name: Prepare package (Linux/macOS)
          if: runner.os != 'Windows'
          run: |
            mkdir -p release
            cp build/Release/lambda_plotter release/
            tar -czvf lambda_plotter-${{ runner.os }}.tar.gz -C release .

        - name: Prepare package (Windows)
          if: runner.os == 'Windows'
          run: |
            Compress-Archive -Path build/Release/lambda_plotter.exe -DestinationPath lambda_plotter-${{ runner.os }}.zip
        
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: release-asset-${{ runner.os }}
            path: |
              lambda_plotter-*.tar.gz
              lambda_plotter-*.zip
        
    create_release:
        name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        needs: build
        runs-on: ubuntu-latest
        permissions: 
            contents: write

        steps:
            - name: Download release assests
              uses: actions/download-artifact@v4
              with:
                path: release-assets
            
            - name: Create Release and Upload Assets
              uses: softprops/action-gh-release@v2
              with:
                files: release-assets/*/*
                generate_release_notes: true

